<?php

use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class AdminPrivillegeTest extends TestCase
{
    private $admin;
    private $permission;
    private $role;
    public function testOne()
    {
        // admin add role and del role
        $this->assertTrue(0 == $this->admin->roles()->get()->count());
        $this->admin->roles()->attach($this->role);
        $this->assertTrue(1 == $this->admin->roles()->get()->count());
        $this->admin->roles()->detach($this->role);
        $this->assertTrue(0 == $this->admin->roles()->get()->count());

        // role add and del permission
        $this->assertTrue(0 == $this->role->permissions()->get()->count());
        $this->role->permissions()->attach($this->permission);
        $this->assertTrue(1 == $this->role->permissions()->get()->count());
        $this->role->permissions()->detach($this->permission);
        $this->assertTrue(0 == $this->role->permissions()->get()->count());
    }

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->admin = \App\Admin::create([
            'name' => 'test',
            'email' => 'test@163.com',
            'password' => '222'
        ]);
        $this->permission = \App\AdmPermission::create([
            'name' => 'per1'
        ]);
        $this->role = \App\AdmRole::create([
            'name' => 'role1'
        ]);
    }
    public function tearDown()
    {
        $this->admin->delete();
        $this->permission->delete();
        $this->role->delete();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
